---
title: "FI Soccer Kaggle Competition"
output: html_notebook
---
### Explortory Data Analysis
```{r}
pkg <- c("dplyr",
         "RSQLite",
         "tidyr",
         "DBI",
         "e1071",
         "rpart",
         "glmnet",
         "plotly")

pkg_load <- lapply(pkg, require, character.only = T, quietly = TRUE)

# connect to the db
conn <- dbConnect(drv = RSQLite::SQLite(),
                        dbname = "data/database.sqlite")
#list tables
tbl_list <- db_list_tables(conn)

# query tables
for (i in seq_along(tbl_list)){
    assign(tbl_list[i], dbGetQuery(conn, paste("select * from", tbl_list[i])))
}

# Combine Country and League
LeagueInfo <- full_join(League, Country, by = c("id")) %>% 
    setNames(c("league.id", "country.id", "league.name", "country.name"))

rm(list = c("League", "Country", "sqlite_sequence"))
```

Exploratory Data Analysis on Match Data Set

```{r}
rowSums(Match %>% is.na())

var_player <- Match %>% 
    colnames %>%
    grep("player", x = ., ignore.case = T, value = T)

var_stat <- Match %>% 
    select(goal:possession) %>%
    colnames

var_ratio <- Match %>% 
    select(B365H:BSA) %>%
    colnames

var_match_info <- Match %>%
    select(1:7) %>%
    colnames

train <- Match %>%
    select(-one_of(var_player),
           -one_of(var_stat),
           -one_of(var_match_info))

colSums(train %>% is.na())

for(i in unique(train$home_team_api_id)) {
#    train[paste("home",i,sep="_")] <- ifelse(train$home_team_api_id == i, 1, 0)
}

for(i in unique(train$away_team_api_id)) {
#    train[paste("away",i,sep="_")] <- ifelse(train$away_team_api_id == i, 1, 0)
}

train <- train %>% 
    select(-home_team_api_id, -away_team_api_id) %>%
    select(-home_team_goal, -away_team_goal) %>%
    select(-(GBH:BSA)) %>%
    select(-(PSH:PSA)) %>%
    select(-(SJH:SJA)) %>%
    .[complete.cases(.),] 

train$outcome <- train$outcome %>% factor()

colSums(train %>% is.na()) %>% sum()



model_linear <- svm(outcome ~ . , data = train, type = "C-classification", kernel = "linear")
model_poly <- svm(outcome ~ . , data = train, type = "C-classification", kernel = "polynomial")
model_sigmoid <- svm(outcome ~ . , data = train, type = "C-classification", kernel = "sigmoid")
```
Read solution set

```{r}
test <- train %>% slice(1:200) %>% select(-outcome)
test_outcome <- train %>% slice(1:200) %>% select(outcome) %>% unlist

pred_linear <- predict(model_linear, test)
sum(pred_linear == test_outcome)

pred_sigmoid <- predict(model_sigmoid, test)
sum(pred_sigmoid == test_outcome)

pred_poly <- predict(model_poly, test)
sum(pred_poly == test_outcome)


```
logistic regression
```{r}

y = train$outcome %>% as.matrix()
x = train %>% select(-outcome) %>% as.matrix()

model_logit <- cv.glmnet(x, y, family="multinomial", alpha = 0)
model_logit$lambda.1se

model_logit_final <- model_logit$glmnet.fit

pred_logit <- predict(model_logit_final,newx=test %>% as.matrix(),s=model_logit$lambda.1se,type='class')
sum(pred_logit == test_outcome)



```


